"Spawns"
{
	"DemonArea"
	{
		"npc_demon_imp"
		{
			"RespawnTime"	"60"
			"MaxSpawn"		"20"
			"BountyGoldMin"	"2"
			"BountyGoldMax"	"3"
			"MatBounty"		"0"
		}

		"npc_dota_necronomicon_archer_3"
		{
			"RespawnTime"	"30"
			"MaxSpawn"		"15"
			"BountyGoldMin"	"2"
			"BountyGoldMax"	"3"
			"MatBounty"		"0"
		}
		
		"npc_dota_broodmother_spiderling"
		{
			"RespawnTime"	"30"
			"MaxSpawn"		"20"
			"BountyGoldMin"	"2"
			"BountyGoldMax"	"3"
			"MatBounty"		"0"
		}
	}	
}